### PR TITLE
Migrate away from deprecated listener condition format

### PR DESCRIPTION
**Pull request by jjungnickel**
This deprecation was introduced in v2.42 of the aws provider, so
bumping requirement `versions.tf`, too.

## what
* Migrates the `condition` blocks away from the deprecated  `field`/`values` variant in favor of the current block-syntax.

## why
* Recent versions of the aws provider do no longer work with lists for hosts/paths.

## references
* https://github.com/terraform-providers/terraform-provider-aws/pull/8268
* https://github.com/terraform-providers/terraform-provider-aws/issues/10586

### CODE REVIEW

**Comment by Gowiem** [comment]
@nitrocode I feel like you should check this one out considering you use this module a bit (I think). 😄

**Review by nitrocode — DISMISSED** [review]

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
