### PR TITLE
Add fixed-response action

### PR DESCRIPTION
**Pull request by ragumix**
## what
* Add an ability to create rules with _**fixed-response**_ action

## why
* There was no ability to create such rules

### CODE REVIEW

**Comment by aknysh** [comment]
@ragumix  thanks for the PR
Please run these commands and commit the changes:

```
make init
make github/init
make readme
```

(it will add the updated GithUb workflows and format README)

thanks

**Comment by ragumix** [comment]
> @ragumix thanks for the PR Please run these commands and commit the changes:
> 
> ```
> make init
> make github/init
> make readme
> ```
> 
> (it will add the updated GithUb workflows and format README)
> 
> thanks

Done.

**Comment by ragumix** [comment]
During the creation of this PR I thought about the following idea: maybe it would be better to create a new variable like **action_type**? But for the saving my time and saving backward compatibility decided to add changes in the existing way.

**Comment by ragumix** [comment]
Hello!
Any news about this PR? Will it be reviewed in the near future?
It's really helpful feature to have a possibility to add a rule not only with "Forward" type action.
Please consider this PR.

**Pull request closed without merging**
