### PR TITLE
Add enabled variable

### PR DESCRIPTION
**Pull request by nitrocode**

### CODE REVIEW

**Review by Gowiem — DISMISSED** [review]
Looks like this repo doesn't have the GH actions merged yet. @osterman is the plan still to update all repos using automation or should we be trying to update them as we come across em?

Updates look good though @nitrocode :shipit: once tests pass and what not.

**Comment by osterman** [comment]
See #28

**Comment by osterman** [comment]
@Gowiem - yep, ping me anytime you guys need a repo updated. I have a script to upgrade it pretty quickly that I run locally.

**Comment by osterman** [comment]
@nitrocode usually when you add counts, you also need to update outputs to use join-splat syntax.

**Comment by osterman** [comment]
See https://github.com/cloudposse/terraform-aws-cloudwatch-flow-logs/issues/6

**Comment by nitrocode** [comment]
@osterman Tests are failing because the s3 bucket is already created...

> TestExamplesComplete 2020-06-17T12:12:13Z command.go:121: Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

Should I change the bucket name in the test?

**Comment by osterman** [comment]
@nitrocode could you add this? https://github.com/cloudposse/terraform-aws-alb/pull/42/files

Just generate a random attribute. It will affect the outputs though, so the comparisons need updating.

**Review by osterman — APPROVED** [review]

**Comment by osterman** [comment]
Test fixed

**Comment by nitrocode** [comment]
Sweet! Thanks for fixing the test

**Pull request merged**
