### PR TITLE
feat: add scope to oidc listener rule configuration

### PR DESCRIPTION
**Pull request by jhosteny**
## what
* expose scopes for OIDC / cognito

## why
* allow the default provider scopes to be expanded upon

### CODE REVIEW

**Comment by aknysh** [comment]
@jhosteny  please run these commands:

```
make init
make readme/deps
make readme

terraform fmt (on all TF files including the example)
```

we usually can do it with GitOps, but for this fork we get this error 

```
Permission to carnegierobotics/terraform-aws-alb-ingress.git denied to cloudpossebot
```

Or you can allow the bot to execute the commands on the fork.

Thanks

**Comment by jhosteny** [comment]
@aknysh sorry about that. I forgot to redo it after I made my second change.

**Review by SweetOps — APPROVED** [review]

**Pull request merged**
